# app/github_client.py (interface sketch)
class GitHubClient:
    def __init__(self, pat: str): ...

    def get_recent_commits(self, author_name: str, time_range: str): ...

    def get_recent_pull_requests(self, author_name: str, time_range: str): ...
